[package]
name = "aster-proxy"
version = "1.1.4"
authors = ["wayslog <zxs867179@gmail.com>"]
description = "A light, fast and powerful cache proxy written in Rust."
homepage = "https://github.com/wayslog/aster"
repository = "https://github.com/wayslog/aster"
documentation = "https://docs.rs/aster-proxy"
license = "MIT"
readme = "README.md"
categories = ["asynchronous", "network-programming", "caching", "database"]
keywords = [ "cache", "redis", "memcache", "twemproxy"]
edition="2018"

[workspace]
members = [
    "libaster",
    "a2/adam",
    "./",
]
default-members = ["libaster", "./"]

[[bin]]
name = "aster-proxy"
path = "bin/proxy.rs"

[lib]
name = "aster"
path = "src/lib.rs"

[dependencies]
libaster = {path = "libaster", version = "1.1.4", features=["metrics"]}

[profile.release]
debug = true
lto = true
