[package]
name = "aster-proxy"
version = "0.1.4"
authors = ["wayslog"]
description = "A light, fast and powerful cache proxy in Rust."
homepage = "https://github.com/wayslog/aster"
repository = "https://github.com/wayslog/aster"
documentation = "https://docs.rs/aster-proxy"
license = "MIT"
readme = "README.md"
categories = ["asynchronous", "network-programming", "caching", "database"]
keywords = [ "cache", "redis", "memcache", "twemproxy"]
edition="2018"

[lib]
name="libaster"
path="src/lib.rs"

[[bin]]
name="aster"
path="bin/main.rs"

[[bench]]
name="aster_bench"
harness = false

[dev-dependencies]
criterion = "0.2"

[dependencies]
byteorder = "1.*"
tokio = "0.1"
tokio-codec="0.1"
log="0.4"
env_logger="0.6"
bytes="0.4"
lazy_static="1.1"
btoi="0.4"
futures= "0.1"
toml="0.4"
serde="1.0"
serde_derive="1.0"
itoa="0.4"
net2="0.2"
md5="0.6"
hashbrown = "0.1"
num_cpus = "1.8"

[profile.release]
debug = true
lto = true