[[clusters]]
name = "standalone"
listen_addr = "0.0.0.0:6380"
cache_type = "redis"
thread = 2
servers = [
    "redis-standalone:6379:1 redis-1",
]
password = "front-standalone-secret"
backend_password = "backend-standalone-secret"
backend_resp_version = "resp3"

[[clusters]]
name = "cluster"
listen_addr = "0.0.0.0:6381"
cache_type = "redis_cluster"
thread = 2
read_from_slave = false
servers = [
    "redis-node-1:7000",
    "redis-node-2:7001",
    "redis-node-3:7002",
]
auth = { password = "front-cluster-secret", users = [
    { username = "ops", password = "ops-secret" }
] }
backend_password = "backend-cluster-secret"
backend_resp_version = "resp3"
